# Generated by Django 2.2.3 on 2020-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='picture',
            field=models.ImageField(null=True, upload_to='pokemons'),
        ),
    ]
